# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb25f327ea0481aacc87e2ba4196c107ff46344564dc8ac846ca9f44f8ab4e6ab3a2266a21eb12bb639164259553205fe9bfd30331885c5864f19d121a47a96

test:
  secret_key_base: 5d5bb70f705c08094d2839d600ae7305332a75b035cd731025c21c9d78a5bb839ef75b9abfc14f016195e26a9d1719c3ef133f8b74f00d73d2e2ef7f6d8029b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
